# Generated by Django 6.0.6 on 2026-06-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barnameh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shbarnameh', models.CharField(max_length=10)),
                ('Barnameh_date', models.CharField(max_length=10)),
                ('driver_fname', models.CharField(max_length=100)),
                ('driver_lname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=11)),
            ],
        ),
    ]
