# Generated by Django 6.0.6 on 2026-06-20 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managebar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_code', models.CharField(max_length=30)),
                ('account_holder', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_code', models.CharField(max_length=15)),
                ('owner_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='barnameh',
            name='amount_base',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barnameh',
            name='amount_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barnameh',
            name='pay_date',
            field=models.CharField(default='1405/03/30', max_length=10),
        ),
        migrations.AddField(
            model_name='barnameh',
            name='plate_number',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='barnameh',
            name='purpose',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='barnameh',
            name='type_pay',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='barnameh',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managebar.banks'),
        ),
        migrations.AddField(
            model_name='barnameh',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managebar.receiver'),
        ),
    ]
