# Generated by Django 6.0.6 on 2026-06-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managebar', '0002_banks_receiver_barnameh_amount_base_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banks',
            new_name='Bank',
        ),
    ]
