# Generated by Django 6.0.6 on 2026-06-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managebar', '0003_rename_banks_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barnameh',
            old_name='Barnameh_date',
            new_name='barnameh_date',
        ),
        migrations.AddField(
            model_name='barnameh',
            name='status',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
