# Generated by Django 6.0.6 on 2026-06-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managebar', '0004_rename_barnameh_date_barnameh_barnameh_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
